feat: add headers to http error responses
influxdata/influxdb-client-js pull request #1019
Opened 2024-07-24 23:44 UTC by twosdai

Fixes #

## Proposed Changes

Adds headers to the HTTP error response.  Fixes: https://github.com/influxdata/influxdb-client-js/issues/1018

## Checklist

- [] CHANGELOG.md updated
- [x ] Rebased/mergeable
- [x ] A test has been added if appropriate
- [x ] `yarn test` completes successfully
- [ x] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [ x] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

2024-07-24 23:48 UTC, twosdai commented
I am not super familiar with this repo, and this is my first contribution here. Please take a bit more time and review the code. Happy to make any changes you callout. 

The basic idea of this change is to include a headers object in the HttpError thrown by influx. There are multiple different "types" of header formats, I chose to boil them down to the internal format which is basically just a simple `Record<string, string>` This means that for the browser client we need to go over each header value and map it into a object and then pass it in. Since the default `Headers` from the response object will cause typescript to error out at compile time.

2024-07-25 08:54 UTC, bednar requested changes
Thank you for your PR! 👍 Before we can proceed with accepting it, there are a few requirements that need to be met:

2024-07-25 08:54 UTC, bednar commented on packages/core/src/impl/browser/FetchTransport.ts
> +          headersToBeReturned
Please use our build-in function `getResponseHeaders(response)`:

```suggestion
          getResponseHeaders(response)
```

2024-07-25 08:54 UTC, bednar commented on packages/core/src/impl/browser/FetchTransport.ts
> +        headersToBeReturned
Please use our build-in function `getResponseHeaders(response)`:

```suggestion
          getResponseHeaders(response)
```

2024-07-25 08:54 UTC, bednar commented on packages/core/src/impl/browser/FetchTransport.ts
> +      })
Is not necessary, please use our build-in function `getResponseHeaders(response)`:

```suggestion
```

2024-07-25 08:54 UTC, bednar commented on packages/core/src/errors.ts
> +    headers?: HttpHeaders
Let's change type to: `HttpHeaders | undefined`:
```suggestion
    headers?: HttpHeaders | undefined
```

2024-07-25 08:54 UTC, bednar commented on packages/core/src/errors.ts
> +    }
Simplify to:

```suggestion
    this.headers = headers
```

2024-07-25 13:35 UTC, twosdai commented
@bednar  Thanks for the comments, I've implemented the change here:  https://github.com/influxdata/influxdb-client-js/pull/1019/commits/c3fb1fa341485af87aff9439277eb6bc91fa456f

Let me know if you need / want anything else.

2024-07-25 13:53 UTC, bednar requested changes
@twosdai, thank you again for your fantastic PR! 👍

Could you please update the `CHANGELOG.md` with the following entry:

```
### Features

1. [1019](https://github.com/influxdata/influxdb-client-js/pull/1019/): Propagates headers from HTTP response when an error is returned from the server.
```

Once that's done, we'll be ready to merge this PR.

2024-07-25 15:23 UTC, twosdai commented
@bednar  See the commit here for the changelog update: https://github.com/influxdata/influxdb-client-js/pull/1019/commits/643e6f433d2237d2ec9fe278db1708f0cef7a84f

Let me know if you need anything else! Thanks for the quick review :)

2024-07-25 17:08 UTC, bednar approved these changes
LGTM 🚀

2024-07-25 17:10 UTC, merged