added test to check if quotes are escaped
influxdata/influxdb-client-js pull request #432
Opened 2022-04-08 17:12 UTC by sezanzeb

## Proposed Changes

Just adds a single test. I was investigating how to use `flux` but couldn't see if this escapes and prevents injection attacks.

## Checklist

- [ ] CHANGELOG.md updated < I guess adding a test isn't really something worth mentioning there
- [ ] Rebased/mergeable
- [x] A test has been added if appropriate
- [x] `yarn test` completes successfully
- [x] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [ ] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed) < Dude, just take it or leave it. I don't care about having any rights about those 8 lines of code.

2022-04-08 18:16 UTC, sranka commented
Thank @sezanzeb you for a PR, but I think that your changes do not bring any additional value to this library. The `flux` tagged template is designed exactly for the purpose that you double-checked, it is properly documented this way in https://influxdata.github.io/influxdb-client-js/influxdb-client.flux.html .  All the possible value types and escape sequences are already tested thoroughly in `flux.test.ts`. The only possible (but not a necessary improvement) would be to add

```
        if (pair.value !== undefined) {
          expect(flux`${pair.value}`.toString()).equals(pair.flux)
        } else {
          expect(() => flux`${pair.value}`.toString()).to.throw(
            "Unsupported parameter literal 'undefined' at index: 0, type: undefined"
          )
        }
```
right after 

https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/test/unit/query/flux.test.ts#L119 

it will then extra test all parameter types and escape sequences within the flux tagged template.

2022-04-08 18:29 UTC, sranka requested changes
Thank @sezanzeb you for a PR, but I think that your changes do not bring any additional value to this library. The `flux` tagged template is designed exactly for the purpose that you double-checked, it is properly documented this way in https://influxdata.github.io/influxdb-client-js/influxdb-client.flux.html .  All the possible value types and escape sequences are already tested thoroughly in `flux.test.ts`. A possible (but not a necessary improvement) would be to add

```
        if (pair.value !== undefined) {
          expect(flux`${pair.value}`.toString()).equals(pair.flux)
        } else {
          expect(() => flux`${pair.value}`.toString()).to.throw(
            "Unsupported parameter literal 'undefined' at index: 0, type: undefined"
          )
        }
```
right after 

https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/test/unit/query/flux.test.ts#L119 

it will then extra test all parameter types and escape sequences within the flux tagged template.

2022-04-08 18:31 UTC, sezanzeb commented
There is 

```
  it('processes a simple nested flux template', () => {
    const flux1 = flux`from(bucket:"my-bucket")`
    expect(flux`${flux1} |> range(start: ${0})")`.toString()).equals(
      'from(bucket:"my-bucket") |> range(start: 0)")'
    )
  })
```

but it is different. The new test that I added tries to insert a string containing double-quotes into another set of double-quotes. There is no test that expects an escaped double-quote: `\"`

2022-04-09 06:24 UTC, sranka commented
Thank you for your feedback.

2022-04-09 06:24 UTC, closed without merging